kubernetes-data-platform:
  presto:
    workers: 2
    jvm:
      maxHeapSize: 1536M
    deploy:
      container:
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 1
    task:
      writerCount: 1