kubernetes-data-platform:
  presto:
    workers: 4
    query:
      maxMemory: 80GB
      maxMemoryPerNode: 45GB
      maxTotalMemoryPerNode: 46GB
      heapHeadroomPerNode: 1GB
    jvm:
      maxHeapSize: 48000M
    deploy:
      container:
        resources:
          limits:
            memory: 50Gi
            cpu: 8
          requests:
            memory: 50Gi
            cpu: 8
    task:
      writerCount: 4
