kubernetes-data-platform:
  presto:
    workers: 2
    query:
      maxMemory: 20GB
      maxMemoryPerNode: 12GB
      maxTotalMemoryPerNode: 13GB
      heapHeadroomPerNode: 1GB
    jvm:
      maxHeapSize: 23000M
    deploy:
      container:
        resources:
          limits:
            memory: 15Gi
            cpu: 3
          requests:
            memory: 15Gi
            cpu: 3
    task:
      writerCount: 4
