kubernetes-data-platform:
  presto:
    workers: 2
    query:
      maxMemory: 40GB
      maxMemoryPerNode: 20GB
      maxTotalMemoryPerNode: 21GB
      heapHeadroomPerNode: 1GB
    jvm:
      maxHeapSize: 23000M
    deploy:
      container:
        resources:
          limits:
            memory: 25Gi
            cpu: 4
          requests:
            memory: 25Gi
            cpu: 4
    task:
      writerCount: 4