kubernetes-data-platform:
  presto:
    workers: 2
    query:
      maxMemory: 10GB
      maxMemoryPerNode: 5GB
      maxTotalMemoryPerNode: 5.5GB
      heapHeadroomPerNode: 0.75GB
    jvm:
      maxHeapSize: 10240M
    deploy:
      container:
        resources:
          limits:
            memory: 12Gi
            cpu: 3
          requests:
            memory: 12Gi
            cpu: 3
    task:
      writerCount: 4